<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SpeedHackMod</AssemblyName>
    <RootNamespace>SpeedHackMod</RootNamespace>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CesiumLoader.SDK\CesiumLoader.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- 游戏热更程序集: 业务代码直接用的类型 -->
    <Reference Include="AstralParty.Runtime">
      <HintPath>..\..\..\..\extracted_dlls\AstralParty.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
