# gen_winmm_exports.ps1
# 从系统 winmm.dll 提取导出名, 生成 C++(MSVC) 转发桩文件 generated_forwards.cpp。
# 用法: pwsh gen_winmm_exports.ps1 -OutFile generated_forwards.cpp
#
# 依赖: VS2022 自带 dumpbin.exe(或任意能输出 /exports 的工具)。

param(
    [string]$OutFile = "C:\src\Study\astralparty\modding\msvc\src\CesiumLoader\generated_forwards.cpp"
)

$dumpbin = 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\dumpbin.exe'
$syswinmm = 'C:\Windows\System32\winmm.dll'

# dumpbin /exports 输出格式(最后一列是名字):
#    1    0 00001560 CloseDriver
#    2    1 0000A580 DefDriverProc
#    3    2 000019F0 DriverCallback
$raw = & $dumpbin /exports $syswinmm 2>$null | ForEach-Object {
    if ($_ -match '^\s*\d+\s+[0-9A-F]+\s+[0-9A-F]+\s+(\S+)\s*$') { $matches[1] }
} | Where-Object { $_ }

# 已由 exports.cpp 手写精确签名的导出(去重,避免重复定义)
$already = @(
    'DllMain','ap_console_write','ap_console_write_w',
    'timeBeginPeriod','timeEndPeriod','timeGetTime',
    'waveInAddBuffer','waveInClose','waveInGetDevCapsA','waveInGetDevCapsW','waveInGetNumDevs',
    'waveInOpen','waveInPrepareHeader','waveInReset','waveInStart','waveInUnprepareHeader',
    'waveOutClose','waveOutGetDevCapsA','waveOutGetDevCapsW','waveOutGetNumDevs','waveOutGetPosition',
    'waveOutOpen','waveOutPrepareHeader','waveOutReset','waveOutUnprepareHeader','waveOutWrite'
)

# 常用函数参数个数表(x64 下用 uintptr_t 透传, 依据 mmsystem.h 知识; 未知默认 4)
$sig = @{
    'PlaySoundA'=3; 'PlaySoundW'=3; 'PlaySound'=3; 'sndPlaySoundA'=2; 'sndPlaySoundW'=2; 'sndPlaySound'=2;
    'OpenDriver'=4; 'CloseDriver'=2; 'SendDriverMessage'=4; 'GetDriverModuleHandle'=2; 'DrvGetModuleHandle'=2; 'DefDriverProc'=4; 'DriverCallback'=6; 'WOWAppExit'=2;
    'auxGetNumDevs'=0; 'auxGetDevCapsA'=3; 'auxGetDevCapsW'=3; 'auxGetVolume'=2; 'auxSetVolume'=2; 'auxOutMessage'=4;
    'joyGetNumDevs'=0; 'joyGetDevCapsA'=3; 'joyGetDevCapsW'=3; 'joyGetPos'=2; 'joyGetPosEx'=2; 'joySetCapture'=4; 'joyReleaseCapture'=2; 'joyGetThreshold'=2; 'joySetThreshold'=2; 'joyConfigChanged'=1;
    'mixerGetNumDevs'=0; 'mixerGetDevCapsA'=3; 'mixerGetDevCapsW'=3; 'mixerOpen'=6; 'mixerClose'=1; 'mixerGetID'=3; 'mixerGetLineControlsA'=3; 'mixerGetLineControlsW'=3; 'mixerGetLineInfoA'=3; 'mixerGetLineInfoW'=3; 'mixerGetControlDetailsA'=3; 'mixerGetControlDetailsW'=3; 'mixerSetControlDetails'=3; 'mixerMessage'=4;
    'midiInGetNumDevs'=0; 'midiInGetDevCapsA'=3; 'midiInGetDevCapsW'=3; 'midiInOpen'=6; 'midiInClose'=1; 'midiInPrepareHeader'=3; 'midiInUnprepareHeader'=3; 'midiInAddBuffer'=3; 'midiInStart'=1; 'midiInStop'=1; 'midiInReset'=1; 'midiInGetErrorTextA'=3; 'midiInGetErrorTextW'=3; 'midiInGetID'=2; 'midiInMessage'=4; 'midiConnect'=3; 'midiDisconnect'=3;
    'midiOutGetNumDevs'=0; 'midiOutGetDevCapsA'=3; 'midiOutGetDevCapsW'=3; 'midiOutOpen'=6; 'midiOutClose'=1; 'midiOutPrepareHeader'=3; 'midiOutUnprepareHeader'=3; 'midiOutShortMsg'=2; 'midiOutLongMsg'=3; 'midiOutReset'=1; 'midiOutCachePatches'=3; 'midiOutCacheDrumPatches'=3; 'midiOutGetVolume'=2; 'midiOutSetVolume'=2; 'midiOutGetErrorTextA'=3; 'midiOutGetErrorTextW'=3; 'midiOutGetID'=2; 'midiOutMessage'=4;
    'waveInGetErrorTextA'=3; 'waveInGetErrorTextW'=3; 'waveInGetID'=2; 'waveInMessage'=4;
    'waveOutGetVolume'=2; 'waveOutSetVolume'=2; 'waveOutGetID'=2; 'waveOutMessage'=4; 'waveOutGetErrorTextA'=3; 'waveOutGetErrorTextW'=3; 'waveOutBreakLoop'=1; 'waveOutPause'=1; 'waveOutRestart'=1;
    'timeGetSystemTime'=2; 'timeSetEvent'=5; 'timeKillEvent'=1; 'timeGetDevCaps'=2;
    'mciSendCommandA'=4; 'mciSendCommandW'=4; 'mciSendStringA'=4; 'mciSendStringW'=4; 'mciGetDeviceIDA'=1; 'mciGetDeviceIDW'=1; 'mciGetErrorStringA'=3; 'mciGetErrorStringW'=3; 'mciGetCreatorTask'=1; 'mciGetYieldProc'=2; 'mciSetYieldProc'=3; 'mciExecute'=1; 'mciFree'=1;
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// AUTO-GENERATED by gen_winmm_exports.ps1 - 完整 winmm 转发桩 (C++/MSVC)')
[void]$sb.AppendLine('// 每个函数转发到系统 winmm.dll。x64 下用 uintptr_t 透传(整数/指针参数经')
[void]$sb.AppendLine('// RCX/RDX/R8/R9+栈, 浮点经 XMM 不受影响)。每个函数自带 static 缓存函数指针。')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include "loader.h"')
[void]$sb.AppendLine('#include <windows.h>')
[void]$sb.AppendLine('#include <cstdint>')
[void]$sb.AppendLine('')

$count = 0
foreach ($name in $raw) {
    if ($already -contains $name) { continue }
    $n = $sig[$name]
    if ($null -eq $n) { $n = 4 }
    if ($n -gt 0) { $idx = @(0..($n-1)) } else { $idx = @() }
    $params = ($idx | ForEach-Object { "uintptr_t a$($_)" }) -join ', '
    $args = ($idx | ForEach-Object { "a$($_)" }) -join ', '
    $ptypes = (@('uintptr_t') * $n) -join ', '
    [void]$sb.AppendLine("extern `"C`" __declspec(dllexport) uintptr_t WINAPI $name($params)")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine('    maybe_start_boot();')
    [void]$sb.AppendLine("    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)($ptypes)>(real_winmm_fn(`"$name`"));")
    [void]$sb.AppendLine("    return fn($args);")
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine('')
    $count++
}

[void]$sb.AppendLine("// 共 $count 个转发函数(自动生成)")
Set-Content -Path $OutFile -Value $sb.ToString() -Encoding UTF8
Write-Host "已生成 $count 个转发函数 -> $OutFile"
