// AUTO-GENERATED by gen_winmm_exports.ps1 - 完整 winmm 转发桩 (C++/MSVC)
// 每个函数转发到系统 winmm.dll。x64 下用 uintptr_t 透传(整数/指针参数经
// RCX/RDX/R8/R9+栈, 浮点经 XMM 不受影响)。每个函数自带 static 缓存函数指针。

#include "loader.h"
#include <windows.h>
#include <cstdint>

extern "C" __declspec(dllexport) uintptr_t WINAPI CloseDriver(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("CloseDriver"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI DefDriverProc(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("DefDriverProc"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI DriverCallback(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("DriverCallback"));
    return fn(a0, a1, a2, a3, a4, a5);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI DrvGetModuleHandle(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("DrvGetModuleHandle"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI GetDriverModuleHandle(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("GetDriverModuleHandle"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI OpenDriver(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("OpenDriver"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI PlaySound(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("PlaySound"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI PlaySoundA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("PlaySoundA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI PlaySoundW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("PlaySoundW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI SendDriverMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("SendDriverMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI WOWAppExit(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("WOWAppExit"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI auxGetDevCapsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("auxGetDevCapsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI auxGetDevCapsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("auxGetDevCapsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI auxGetNumDevs()
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)()>(real_winmm_fn("auxGetNumDevs"));
    return fn();
}

extern "C" __declspec(dllexport) uintptr_t WINAPI auxGetVolume(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("auxGetVolume"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI auxOutMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("auxOutMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI auxSetVolume(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("auxSetVolume"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyConfigChanged(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("joyConfigChanged"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyGetDevCapsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("joyGetDevCapsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyGetDevCapsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("joyGetDevCapsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyGetNumDevs()
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)()>(real_winmm_fn("joyGetNumDevs"));
    return fn();
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyGetPos(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("joyGetPos"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyGetPosEx(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("joyGetPosEx"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyGetThreshold(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("joyGetThreshold"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joyReleaseCapture(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("joyReleaseCapture"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joySetCapture(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("joySetCapture"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI joySetThreshold(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("joySetThreshold"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciDriverNotify(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciDriverNotify"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciDriverYield(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciDriverYield"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciExecute(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("mciExecute"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciFreeCommandResource(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciFreeCommandResource"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetCreatorTask(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("mciGetCreatorTask"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetDeviceIDA(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("mciGetDeviceIDA"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetDeviceIDFromElementIDA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciGetDeviceIDFromElementIDA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetDeviceIDFromElementIDW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciGetDeviceIDFromElementIDW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetDeviceIDW(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("mciGetDeviceIDW"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetDriverData(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciGetDriverData"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetErrorStringA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciGetErrorStringA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetErrorStringW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciGetErrorStringW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciGetYieldProc(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("mciGetYieldProc"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciLoadCommandResource(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciLoadCommandResource"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciSendCommandA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciSendCommandA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciSendCommandW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciSendCommandW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciSendStringA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciSendStringA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciSendStringW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciSendStringW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciSetDriverData(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciSetDriverData"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mciSetYieldProc(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mciSetYieldProc"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiConnect(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiConnect"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiDisconnect(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiDisconnect"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInAddBuffer(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInAddBuffer"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInClose(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("midiInClose"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInGetDevCapsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInGetDevCapsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInGetDevCapsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInGetDevCapsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInGetErrorTextA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInGetErrorTextA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInGetErrorTextW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInGetErrorTextW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInGetID(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("midiInGetID"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInGetNumDevs()
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)()>(real_winmm_fn("midiInGetNumDevs"));
    return fn();
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInOpen(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInOpen"));
    return fn(a0, a1, a2, a3, a4, a5);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInPrepareHeader(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInPrepareHeader"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInReset(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("midiInReset"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInStart(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("midiInStart"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInStop(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("midiInStop"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiInUnprepareHeader(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiInUnprepareHeader"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutCacheDrumPatches(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutCacheDrumPatches"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutCachePatches(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutCachePatches"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutClose(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("midiOutClose"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetDevCapsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutGetDevCapsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetDevCapsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutGetDevCapsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetErrorTextA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutGetErrorTextA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetErrorTextW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutGetErrorTextW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetID(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("midiOutGetID"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetNumDevs()
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)()>(real_winmm_fn("midiOutGetNumDevs"));
    return fn();
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutGetVolume(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("midiOutGetVolume"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutLongMsg(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutLongMsg"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutOpen(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutOpen"));
    return fn(a0, a1, a2, a3, a4, a5);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutPrepareHeader(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutPrepareHeader"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutReset(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("midiOutReset"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutSetVolume(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("midiOutSetVolume"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutShortMsg(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("midiOutShortMsg"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiOutUnprepareHeader(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiOutUnprepareHeader"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamClose(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamClose"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamOpen(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamOpen"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamOut(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamOut"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamPause(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamPause"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamPosition(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamPosition"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamProperty(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamProperty"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamRestart(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamRestart"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI midiStreamStop(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("midiStreamStop"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerClose(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("mixerClose"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetControlDetailsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetControlDetailsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetControlDetailsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetControlDetailsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetDevCapsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetDevCapsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetDevCapsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetDevCapsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetID(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetID"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetLineControlsA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetLineControlsA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetLineControlsW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetLineControlsW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetLineInfoA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetLineInfoA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetLineInfoW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerGetLineInfoW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerGetNumDevs()
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)()>(real_winmm_fn("mixerGetNumDevs"));
    return fn();
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerOpen(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerOpen"));
    return fn(a0, a1, a2, a3, a4, a5);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mixerSetControlDetails(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mixerSetControlDetails"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmDrvInstall(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmDrvInstall"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmGetCurrentTask(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmGetCurrentTask"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmTaskBlock(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmTaskBlock"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmTaskCreate(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmTaskCreate"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmTaskSignal(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmTaskSignal"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmTaskYield(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmTaskYield"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioAdvance(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioAdvance"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioAscend(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioAscend"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioClose(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioClose"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioCreateChunk(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioCreateChunk"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioDescend(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioDescend"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioFlush(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioFlush"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioGetInfo(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioGetInfo"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioInstallIOProcA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioInstallIOProcA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioInstallIOProcW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioInstallIOProcW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioOpenA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioOpenA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioOpenW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioOpenW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioRead(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioRead"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioRenameA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioRenameA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioRenameW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioRenameW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioSeek(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioSeek"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioSendMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioSendMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioSetBuffer(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioSetBuffer"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioSetInfo(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioSetInfo"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioStringToFOURCCA(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioStringToFOURCCA"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioStringToFOURCCW(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioStringToFOURCCW"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmioWrite(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmioWrite"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI mmsystemGetVersion(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("mmsystemGetVersion"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI sndPlaySoundA(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("sndPlaySoundA"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI sndPlaySoundW(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("sndPlaySoundW"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI timeGetDevCaps(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("timeGetDevCaps"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI timeGetSystemTime(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("timeGetSystemTime"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI timeKillEvent(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("timeKillEvent"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI timeSetEvent(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("timeSetEvent"));
    return fn(a0, a1, a2, a3, a4);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveInGetErrorTextA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveInGetErrorTextA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveInGetErrorTextW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveInGetErrorTextW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveInGetID(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("waveInGetID"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveInGetPosition(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveInGetPosition"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveInMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveInMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveInStop(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveInStop"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutBreakLoop(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("waveOutBreakLoop"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutGetErrorTextA(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutGetErrorTextA"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutGetErrorTextW(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutGetErrorTextW"));
    return fn(a0, a1, a2);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutGetID(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("waveOutGetID"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutGetPitch(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutGetPitch"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutGetPlaybackRate(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutGetPlaybackRate"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutGetVolume(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("waveOutGetVolume"));
    return fn(a0, a1);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutMessage(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutMessage"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutPause(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("waveOutPause"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutRestart(uintptr_t a0)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t)>(real_winmm_fn("waveOutRestart"));
    return fn(a0);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutSetPitch(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutSetPitch"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutSetPlaybackRate(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t, uintptr_t, uintptr_t)>(real_winmm_fn("waveOutSetPlaybackRate"));
    return fn(a0, a1, a2, a3);
}

extern "C" __declspec(dllexport) uintptr_t WINAPI waveOutSetVolume(uintptr_t a0, uintptr_t a1)
{
    maybe_start_boot();
    static auto fn = reinterpret_cast<uintptr_t(WINAPI*)(uintptr_t, uintptr_t)>(real_winmm_fn("waveOutSetVolume"));
    return fn(a0, a1);
}

// 共 157 个转发函数(自动生成)

